version: '3.8'

services:
  frontend:
    image: kulukorvaus-front-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: kulukorvaus-front-dev