version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: kulukorvaus-reverseproxy
    depends_on:
      - backend
      - frontend
  backend:
    image: kulukorvaus-back-dev
    build:
      context: ./Backend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./Backend:/usr/src/app
    environment:
      - PORT=3001
    container_name: kulukorvaus-back-dev
  frontend:
    image: kulukorvaus-front-dev
    build:
      context: ./Frontend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./Frontend:/usr/src/app/
    environment:
      - WDS_SOCKET_PORT=0 #Remove this when React Dev Server bug is fixed: https://github.com/facebook/create-react-app/issues/11897
    container_name: kulukorvaus-front-dev